/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <signal.h>
#include <sys/ttycom.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>

#ifdef __STDC__
#define SIG_PF void(*)(int)
#endif

#ifdef DEBUG
#define RPC_SVC_FG
#endif

#define _RPCSVC_CLOSEDOWN 120
extern int _rpcpmstart;		/* Started by a port monitor ? */
extern int _rpcfdtype;		/* Whether Stream or Datagram ? */
extern int _rpcsvcdirty;	/* Still serving ? */

static
void _msgout(msg)
	char *msg;
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, "%s", msg);
	else
		(void) fprintf(stderr, "%s\n", msg);
#else
	syslog(LOG_ERR, "%s", msg);
#endif
}

static int *
_destroy_rpc_1(argp, rqstp)
	void  *argp;
	struct svc_req *rqstp;
{
	return(destroy_rpc_1_svc(rqstp));
}

static int *
_set_value_rpc_1(argp, rqstp)
	set_modify_args  *argp;
	struct svc_req *rqstp;
{
	return(set_value_rpc_1_svc(*argp, rqstp));
}

static get_value_res *
_get_value_rpc_1(argp, rqstp)
	key_args  *argp;
	struct svc_req *rqstp;
{
	return(get_value_rpc_1_svc(*argp, rqstp));
}

static int *
_modify_value_rpc_1(argp, rqstp)
	set_modify_args  *argp;
	struct svc_req *rqstp;
{
	return(modify_value_rpc_1_svc(*argp, rqstp));
}

static int *
_delete_key_rpc_1(argp, rqstp)
	key_args  *argp;
	struct svc_req *rqstp;
{
	return(delete_key_rpc_1_svc(*argp, rqstp));
}

static int *
_exist_rpc_1(argp, rqstp)
	key_args  *argp;
	struct svc_req *rqstp;
{
	return(exist_rpc_1_svc(*argp, rqstp));
}

void
claves_rpc_prog_1(rqstp, transp)
	struct svc_req *rqstp;
	SVCXPRT *transp;
{
	union {
		set_modify_args set_value_rpc_1_arg;
		key_args get_value_rpc_1_arg;
		set_modify_args modify_value_rpc_1_arg;
		key_args delete_key_rpc_1_arg;
		key_args exist_rpc_1_arg;
	} argument;
	char *result;
	bool_t (*xdr_argument)(), (*xdr_result)();
	char *(*local)();

	_rpcsvcdirty = 1;
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
		_rpcsvcdirty = 0;
		return;

	case DESTROY_RPC:
		xdr_argument = xdr_void;
		xdr_result = xdr_int;
		local = (char *(*)()) _destroy_rpc_1;
		break;

	case SET_VALUE_RPC:
		xdr_argument = xdr_set_modify_args;
		xdr_result = xdr_int;
		local = (char *(*)()) _set_value_rpc_1;
		break;

	case GET_VALUE_RPC:
		xdr_argument = xdr_key_args;
		xdr_result = xdr_get_value_res;
		local = (char *(*)()) _get_value_rpc_1;
		break;

	case MODIFY_VALUE_RPC:
		xdr_argument = xdr_set_modify_args;
		xdr_result = xdr_int;
		local = (char *(*)()) _modify_value_rpc_1;
		break;

	case DELETE_KEY_RPC:
		xdr_argument = xdr_key_args;
		xdr_result = xdr_int;
		local = (char *(*)()) _delete_key_rpc_1;
		break;

	case EXIST_RPC:
		xdr_argument = xdr_key_args;
		xdr_result = xdr_int;
		local = (char *(*)()) _exist_rpc_1;
		break;

	default:
		svcerr_noproc(transp);
		_rpcsvcdirty = 0;
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		_rpcsvcdirty = 0;
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	_rpcsvcdirty = 0;
	return;
}
