/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVESRPC_H_RPCGEN
#define _CLAVESRPC_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAX_TEXTO 255
#define MAX_VALUE2 32

typedef char *texto;
#ifdef __cplusplus
extern "C" bool_t xdr_texto(XDR *, texto*);
#elif __STDC__
extern  bool_t xdr_texto(XDR *, texto*);
#else /* Old Style C */
bool_t xdr_texto();
#endif /* Old Style C */


typedef struct {
	u_int vector_floats_len;
	float *vector_floats_val;
} vector_floats;
#ifdef __cplusplus
extern "C" bool_t xdr_vector_floats(XDR *, vector_floats*);
#elif __STDC__
extern  bool_t xdr_vector_floats(XDR *, vector_floats*);
#else /* Old Style C */
bool_t xdr_vector_floats();
#endif /* Old Style C */


struct PaqueteRPC {
	int x;
	int y;
	int z;
};
typedef struct PaqueteRPC PaqueteRPC;
#ifdef __cplusplus
extern "C" bool_t xdr_PaqueteRPC(XDR *, PaqueteRPC*);
#elif __STDC__
extern  bool_t xdr_PaqueteRPC(XDR *, PaqueteRPC*);
#else /* Old Style C */
bool_t xdr_PaqueteRPC();
#endif /* Old Style C */


struct key_args {
	texto key;
};
typedef struct key_args key_args;
#ifdef __cplusplus
extern "C" bool_t xdr_key_args(XDR *, key_args*);
#elif __STDC__
extern  bool_t xdr_key_args(XDR *, key_args*);
#else /* Old Style C */
bool_t xdr_key_args();
#endif /* Old Style C */


struct set_modify_args {
	texto key;
	texto value1;
	int N_value2;
	vector_floats V_value2;
	PaqueteRPC value3;
};
typedef struct set_modify_args set_modify_args;
#ifdef __cplusplus
extern "C" bool_t xdr_set_modify_args(XDR *, set_modify_args*);
#elif __STDC__
extern  bool_t xdr_set_modify_args(XDR *, set_modify_args*);
#else /* Old Style C */
bool_t xdr_set_modify_args();
#endif /* Old Style C */


struct get_value_res {
	int estado;
	texto value1;
	int N_value2;
	vector_floats V_value2;
	PaqueteRPC value3;
};
typedef struct get_value_res get_value_res;
#ifdef __cplusplus
extern "C" bool_t xdr_get_value_res(XDR *, get_value_res*);
#elif __STDC__
extern  bool_t xdr_get_value_res(XDR *, get_value_res*);
#else /* Old Style C */
bool_t xdr_get_value_res();
#endif /* Old Style C */


#define CLAVES_RPC_PROG ((rpc_uint)0x20000001)
#define CLAVES_RPC_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define DESTROY_RPC ((rpc_uint)1)
extern "C" int * destroy_rpc_1(CLIENT *);
extern "C" int * destroy_rpc_1_svc(struct svc_req *);
#define SET_VALUE_RPC ((rpc_uint)2)
extern "C" int * set_value_rpc_1(set_modify_args , CLIENT *);
extern "C" int * set_value_rpc_1_svc(set_modify_args , struct svc_req *);
#define GET_VALUE_RPC ((rpc_uint)3)
extern "C" get_value_res * get_value_rpc_1(key_args , CLIENT *);
extern "C" get_value_res * get_value_rpc_1_svc(key_args , struct svc_req *);
#define MODIFY_VALUE_RPC ((rpc_uint)4)
extern "C" int * modify_value_rpc_1(set_modify_args , CLIENT *);
extern "C" int * modify_value_rpc_1_svc(set_modify_args , struct svc_req *);
#define DELETE_KEY_RPC ((rpc_uint)5)
extern "C" int * delete_key_rpc_1(key_args , CLIENT *);
extern "C" int * delete_key_rpc_1_svc(key_args , struct svc_req *);
#define EXIST_RPC ((rpc_uint)6)
extern "C" int * exist_rpc_1(key_args , CLIENT *);
extern "C" int * exist_rpc_1_svc(key_args , struct svc_req *);

#elif __STDC__
#define DESTROY_RPC ((rpc_uint)1)
extern  int * destroy_rpc_1(CLIENT *);
extern  int * destroy_rpc_1_svc(struct svc_req *);
#define SET_VALUE_RPC ((rpc_uint)2)
extern  int * set_value_rpc_1(set_modify_args , CLIENT *);
extern  int * set_value_rpc_1_svc(set_modify_args , struct svc_req *);
#define GET_VALUE_RPC ((rpc_uint)3)
extern  get_value_res * get_value_rpc_1(key_args , CLIENT *);
extern  get_value_res * get_value_rpc_1_svc(key_args , struct svc_req *);
#define MODIFY_VALUE_RPC ((rpc_uint)4)
extern  int * modify_value_rpc_1(set_modify_args , CLIENT *);
extern  int * modify_value_rpc_1_svc(set_modify_args , struct svc_req *);
#define DELETE_KEY_RPC ((rpc_uint)5)
extern  int * delete_key_rpc_1(key_args , CLIENT *);
extern  int * delete_key_rpc_1_svc(key_args , struct svc_req *);
#define EXIST_RPC ((rpc_uint)6)
extern  int * exist_rpc_1(key_args , CLIENT *);
extern  int * exist_rpc_1_svc(key_args , struct svc_req *);

#else /* Old Style C */
#define DESTROY_RPC ((rpc_uint)1)
extern  int * destroy_rpc_1();
extern  int * destroy_rpc_1_svc();
#define SET_VALUE_RPC ((rpc_uint)2)
extern  int * set_value_rpc_1();
extern  int * set_value_rpc_1_svc();
#define GET_VALUE_RPC ((rpc_uint)3)
extern  get_value_res * get_value_rpc_1();
extern  get_value_res * get_value_rpc_1_svc();
#define MODIFY_VALUE_RPC ((rpc_uint)4)
extern  int * modify_value_rpc_1();
extern  int * modify_value_rpc_1_svc();
#define DELETE_KEY_RPC ((rpc_uint)5)
extern  int * delete_key_rpc_1();
extern  int * delete_key_rpc_1_svc();
#define EXIST_RPC ((rpc_uint)6)
extern  int * exist_rpc_1();
extern  int * exist_rpc_1_svc();
#endif /* Old Style C */

#endif /* !_CLAVESRPC_H_RPCGEN */
