/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <string.h>
#include "clavesRPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
destroy_rpc_1(CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DESTROY_RPC, (xdrproc_t)xdr_void, NULL, (xdrproc_t)xdr_int, (caddr_t)&clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
set_value_rpc_1(set_modify_args arg1, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, SET_VALUE_RPC, (xdrproc_t)xdr_set_modify_args, (caddr_t)&arg1, (xdrproc_t)xdr_int, (caddr_t)&clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

get_value_res *
get_value_rpc_1(key_args arg1, CLIENT *clnt)
{
	static get_value_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GET_VALUE_RPC, (xdrproc_t)xdr_key_args, (caddr_t)&arg1, (xdrproc_t)xdr_get_value_res, (caddr_t)&clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
modify_value_rpc_1(set_modify_args arg1, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, MODIFY_VALUE_RPC, (xdrproc_t)xdr_set_modify_args, (caddr_t)&arg1, (xdrproc_t)xdr_int, (caddr_t)&clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
delete_key_rpc_1(key_args arg1, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DELETE_KEY_RPC, (xdrproc_t)xdr_key_args, (caddr_t)&arg1, (xdrproc_t)xdr_int, (caddr_t)&clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
exist_rpc_1(key_args arg1, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, EXIST_RPC, (xdrproc_t)xdr_key_args, (caddr_t)&arg1, (xdrproc_t)xdr_int, (caddr_t)&clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
