/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clavesRPC.h"

bool_t
xdr_texto(xdrs, objp)
	XDR *xdrs;
	texto *objp;
{

	if (!xdr_string(xdrs, objp, MAX_TEXTO))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vector_floats(xdrs, objp)
	XDR *xdrs;
	vector_floats *objp;
{

	if (!xdr_array(xdrs, (char **)&objp->vector_floats_val, (u_int *)&objp->vector_floats_len, MAX_VALUE2, sizeof(float), (xdrproc_t)xdr_float))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_PaqueteRPC(xdrs, objp)
	XDR *xdrs;
	PaqueteRPC *objp;
{

	if (!xdr_int(xdrs, &objp->x))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->y))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->z))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_key_args(xdrs, objp)
	XDR *xdrs;
	key_args *objp;
{

	if (!xdr_texto(xdrs, &objp->key))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_set_modify_args(xdrs, objp)
	XDR *xdrs;
	set_modify_args *objp;
{

	if (!xdr_texto(xdrs, &objp->key))
		return (FALSE);
	if (!xdr_texto(xdrs, &objp->value1))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->N_value2))
		return (FALSE);
	if (!xdr_vector_floats(xdrs, &objp->V_value2))
		return (FALSE);
	if (!xdr_PaqueteRPC(xdrs, &objp->value3))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_get_value_res(xdrs, objp)
	XDR *xdrs;
	get_value_res *objp;
{

	if (!xdr_int(xdrs, &objp->estado))
		return (FALSE);
	if (!xdr_texto(xdrs, &objp->value1))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->N_value2))
		return (FALSE);
	if (!xdr_vector_floats(xdrs, &objp->V_value2))
		return (FALSE);
	if (!xdr_PaqueteRPC(xdrs, &objp->value3))
		return (FALSE);
	return (TRUE);
}
